### ISSUE TITLE
How to initialize the function

### ISSUE THREAD

**Issue by InternetMedical** [bluecamel/best_checkpoint_copier#1]
dear, your code is a great work. But I still have a problem. Would you mind telling me how to initialize the function? Specifically, what's the x and y should be? It would be appreciated if you show detailed (practical) examples on using the function .

**Comment by bluecamel** [comment]
Hi, there.  Sorry for the delay.  This is all covered in the README.  

> x is the current checkpoint; y is the previously copied checkpoint with the highest/worst score

Please see the README for an example.
